/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ClemsonDB": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "ClemsonEventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "ClemsonSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "ClemsonVpc": {
      "type": "sst.aws.Vpc"
    }
    "CognitoPreSignup": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RideScheduler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RideWorkflow": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}